// Objective-C API for talking to github.com/go-react-native/demo Go package.
//   gobind -lang=objc -prefix=Go github.com/go-react-native/demo
//
// File is generated by gobind. Do not edit.

#ifndef __GoDemo_H__
#define __GoDemo_H__

#include <Foundation/Foundation.h>

@protocol GoDemoEventBus;
@class GoDemoEventBus;

@protocol GoDemoEventBus
- (void)sendEvent:(NSString*)channel message:(NSString*)message;
@end

FOUNDATION_EXPORT NSString* GoDemoHelloWorld(id<GoDemoEventBus> bus);

FOUNDATION_EXPORT NSString* GoDemoReadFile(NSString* baseDir);

FOUNDATION_EXPORT void GoDemoStartListening();

FOUNDATION_EXPORT void GoDemoWriteFile(NSString* baseDir);

@class GoDemoEventBus;

@interface GoDemoEventBus : NSObject <GoDemoEventBus> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (void)sendEvent:(NSString*)channel message:(NSString*)message;
@end

#endif
