// Objective-C API for talking to github.com/sandbox/samples/GoReact/demo Go package.
//   gobind -lang=objc -prefix=Go github.com/sandbox/samples/GoReact/demo
//
// File is generated by gobind. Do not edit.

#ifndef __GoDemo_H__
#define __GoDemo_H__

#include <Foundation/Foundation.h>

@class GoDemoReactComponent;

@interface GoDemoReactComponent : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)type;
- (void)setType:(NSString*)v;
// skipped field ReactComponent.Props with unsupported type: *types.Interface

// skipped field ReactComponent.Children with unsupported type: *types.Slice

@end

FOUNDATION_EXPORT NSString* GoDemoHelloWorld();

FOUNDATION_EXPORT NSString* GoDemoReadFile(NSString* baseDir);

FOUNDATION_EXPORT void GoDemoStartListening();

FOUNDATION_EXPORT void GoDemoWriteFile(NSString* baseDir);

#endif
