// Objective-C API for talking to github.com/go-react-native/demo Go package.
//   gobind -lang=objc -prefix=Go github.com/go-react-native/demo
//
// File is generated by gobind. Do not edit.

#ifndef __GoDemo_H__
#define __GoDemo_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString* GoDemoHelloWorld();

FOUNDATION_EXPORT NSString* GoDemoReadFile(NSString* baseDir);

FOUNDATION_EXPORT void GoDemoStartListening();

FOUNDATION_EXPORT void GoDemoWriteFile(NSString* baseDir);

#endif
